const products = [
  {
    id: 1,
    name: "Victoria Arduino VA388 Black Eagle T3 2 Group (Copper)",
    beforePrice: 21.428,
    price: 19.285,
    discount: 10,
    image: "/Victoria_Arduino_VA388_Black_Eagle_T3_3_Group__Copper_.png",
    additionalImages: [
      "/Victoria_Arduino_VA388_Black_Eagle_T3_3_Group__Copper_2.jpg",

      "/Victoria_Arduino_VA388_Black_Eagle_T3_3_Group__Copper_.png",
    ],
    descriptions: [
      "Height : 49 cm",
      "Depth : 69 cm",
      "Width : 82.5 cm",
      "Weight : 90 kg",
      "Brewing System : Volumetric",
      "Boiler Size : 11.4 lt",
      "Boiler Type : Multi Boiler",
      "Power : 7300 watt",
    ],
  },
  {
    id: 2,
    name: "Hario BGS-400 Beam Heater 220V",
    beforePrice: 714,
    price: 526,
    discount: 25,
    image: "/Hario_BGS-400_Beam_Heater_220V.png",
    additionalImages: ["/Hario_BGS-400_Beam_Heater_220V.png"],
    descriptions: [
      "Article No. : BGS-400",
      "New ETL-certified Halogen Beam Heater",
      "350 W halogen lamp (includes 2 in box)",
      "Rated to 450 W",
      "110-120 V AC",
      "Beam Heater base",
      "Glass panel and heat shield",
      "Three heat shield screws",
    ],
  },
  {
    id: 3,
    name: "SMEG Stand Mixer (SMF02)",
    beforePrice: 1.999,
    price: 1.099,
    discount: 45,
    image: "/smeg-black.png",
    additionalImages: [
      "/smeg-red.png",
      "/smeg-pink.png",
      "/smeg-black.png",
      "/smeg-cream.png",
    ],
    descriptions: [
      "Brand : SMEG",
      "Control Type : Lever",
      "LCD : No",
      "Capacity : 1 L",
      "Dimensions (HxLxW) : 37.8cm x 40.2cm x 22.1cm",
      "Power : 800 watt",
      "Number of Speed : 10",
      "Weight : 9.5 kg",
    ],
  },
  {
    id: 4,
    name: "Hario M-12CP Spoon (Copper)",
    beforePrice: 24,
    price: 21,
    discount: 15,
    image: "/Hario_M-12CP_Spoon__Copper.png",
    additionalImages: ["/Hario_BGS-400_Beam_Heater_220V.png"],
    descriptions: [
      "Brand : Hario",
      "Article No. : M-12CP",
      "Material : Copper and Brass",
      "Berat : 60 gram",
      "Ukuran : Diameter : 5.3 cm, Panjang : 9.6 cm",
      "Warna : Copper",
      "Kapasitas : 12 gram",
      "Made in Japan",
    ],
  },
];
module.exports = products;
